### ISSUE TITLE
Supprimer "public" de l'url

### ISSUE THREAD

**Issue by fab1dev** [bestmomo/laravel5-3-example#10]
Bonjour, 

J'ai déjà réussi à supprimer le public de l'url sur d'autres projets sous laravel, mais je n'y arrive pas du tout avec ce projet en 5.3.

Quelqu'un aurait une idée ? J'ai essayé en déplaçant les fichiers plus réécriture de certains chemins, via .htaccess, en combinant les deux, mais impossible rien ne me convient.

Lorsque j'arrive à un semblant de résultat, la page /login me renvoie une 404, mais la home fonctionne malgré tout sans le "public" sur domaine.dev/ par exemple.

Au plaisir

**Comment by cotiga** [comment]
Hi
Je pense qu'il suffit de faire pointer ton VHost sur le repertoire public
DocumentRoot "/YOUR_LARA_PATH/public"
...

**Comment by fab1dev** [comment]
Salut,
C'est pour faire le project sur des hébergements minimalistes. Aucun problème de perf mais par contre coté configuration c'est très limité pour mon contexte.

J'ai trouvé un semblant de solution en mettant l'ensemble des fichiers du dossier public dans /LARA_PATH et en modifiant server.php à 

-require_once **DIR**.'/public/index.php';
+require_once **DIR**.'/index.php';

Par .htaccess cela me semble plus judicieux et "propre" mais je n'ai pas réussi. Je précise que la problématique concerne un environnement vraiment minimaliste et que j'ai que DocumentRoot et tout est censé se passer à ce niveau, je n'ai pas la possibilité de configuration. 

Merci pour la réponse
