### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by xdendev** [bestmomo/laravel5-3-example#12]
Hello, after steps guide(slow)(mysql) run command: gulp
And go to site page. But i have error 500. What i do not correct?Sorry for my english -_-
P.S. Just white page and nothing .

**Comment by xdendev** [comment]
P.S.S ubuntu 16.04 apache2

**Comment by bestmomo** [comment]
What is the content of error 500 ?

**Comment by xdendev** [comment]
![Screen](https://4.downloader.disk.yandex.ru/disk/30f519ddb70b9c29814415966a05904291fe8a748723e219076bdfb0f0f81764/58284ffb/kK7H8EvH6HN4xT4KPOGbVOWxHGvc9Z6GjcgD0WZQwiKKDf78vCzeIHv-Sa6sZxXa-fcDcpmHmEGdn_lSxAGu_Q%3D%3D?uid=0&filename=%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA%20%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0%20%D0%BE%D1%82%202016-11-13%2014-29-48.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=60986&hid=5670adf9cd9ce17635f8bbae83dd6139&media_type=image&tknv=v2&etag=0211d7295ceb4a547fdbca90399c833a)

**Comment by bestmomo** [comment]
Look in Network tab to read the error détails

**Comment by xdendev** [comment]
in network nothing

**Comment by xdendev** [comment]
help me pls +)

**Comment by bestmomo** [comment]
I'd like to help you but I dont know what happen... I think some local server issue. Can you install a fresh Laravel on it ?

**Comment by xdendev** [comment]
Yes, i install fresh laravel.

**Comment by bestmomo** [comment]
Which PHP version ?

**Comment by xdendev** [comment]
PHP 7.0.8-0ubuntu0.16.04.3

**Comment by xdendev** [comment]
try on PHP 5.4?

**Comment by bestmomo** [comment]
No, PHP 7 is OK

**Comment by xdendev** [comment]
what is fucken problem (;-;)

**Comment by xdendev** [comment]
Maybe i don't have some modules on php?

**Comment by xdendev** [comment]
Can i see your demo online?:)

**Comment by xdendev** [comment]
L@@@@@@@L, I FOUNDED. JUST SET RULES ON FOLDERS:
boostrap/cache 777
storage 777 -R
P.S. DAMN
