### ISSUE TITLE
Swift_TransportException

### ISSUE THREAD

**Issue by whitehorse0** [bestmomo/laravel5-3-example#13]
hi sir, I do user testing registration, and I found an error
 **Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required"**

how to resolve this?
thanks

**Comment by whitehorse0** [comment]
oh yaa, I do not do e-mail configuration file .env, whether it affect?

**Comment by lucassena** [comment]
Yes, you need to configure .env file.

**Comment by whitehorse0** [comment]
like this sir?

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=myusername@gmail.com
MAIL_PASSWORD=myPassword123
MAIL_ENCRYPTION=null

thanks

**Comment by whitehorse0** [comment]
Hi Sir, ill try to registration at local & then i get email notification, but when I do on the server hosting,  I didn't  get an email notification, is there any special settings for it?

thanks

**Comment by bestmomo** [comment]
Hi,
Look at **.env** file in email section, I think you dont have the good parameters for your server.
