### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by iserifith** [bestmomo/laravel5-3-example#15]
I need another section like the blog but only can be access by the registered user.
Either a complete new section or just add an option for the Admin to choose if the post exclusively for registered user. Sorry for my english. Thank you in advance.

**Comment by bestmomo** [comment]
You can add a boolean field in posts table to manage it.

**Comment by iserifith** [comment]
I'm quite new in Laravel and PHP . You might need to explain further what should I do. I'm sorry if this troubling you.

**Comment by bestmomo** [comment]
There are many things to do... 
First add a field in posts table, in migration file : **2014_10_26_172107_create_posts_table.php**
Then you must adapt some forms (create and edit posts) to add this field and also change php code (controller and/or repository) to filter posts with this field.

**Comment by iserifith** [comment]
Sounds too painful. What if add restriction for visitor and can be viewed by registered users. 
And maybe redirect them to login page.

**Comment by bestmomo** [comment]
Sorry but I can see how to add restriction for visitors for some posts without a new posts field.

**Comment by iserifith** [comment]
what I meant was every posts are visible and access only by registered user.

**Comment by iserifith** [comment]
I added @if(session('statut') == 'user' || session('statut') == 'redactor' || session('statut') == 'admin') for classactivesegment for blog. This is fine right?

**Comment by bestmomo** [comment]
If posts must not be accessed by visitors you should forbid blog urls with a new middleware in BlogController and also hide BLOG item in menu.

**Comment by iserifith** [comment]
public function handle($request, Closure $next)
    {
        if (session('statut') === 'visitor')
        {
            return redirect('/');
        }

        return $next($request);
    }

like this?

**Comment by bestmomo** [comment]
No, sorry, just use **auth** middleware.

**Comment by iserifith** [comment]
@bestmomo I got this error when trying to upload it on my subdomain.

`InvalidArgumentException in FileViewFinder.php line 137: View [front.index.blade.php] not found.`

**Comment by bestmomo** [comment]
Check permissions :
_Directories within the **storage** and the **bootstrap/cache** directories should be writable by your web server or Laravel will not run._

**Comment by iserifith** [comment]
@bestmomo is it possible to deploy this project in shared hosting without ssh access ?

**Comment by bestmomo** [comment]
Without **ssh** access you must use **composer** in local and use **ftp** to send all the vendor (idem for updates). And you cant use **artisan** on server to set cache for example. A way for artisan is to use my [nice-artisan](https://github.com/bestmomo/nice-artisan), I didn't create it for this case but why not ?

But the better way is to change hosting to get SSH  ;)
