### ISSUE TITLE
Error cant connect to database

### ISSUE THREAD

**Issue by papablopo** [bestmomo/laravel5-3-example#17]
Im having an error, when try to connect to the database, everything its ok in the configuration, i can connect using mysql workbeanch with the same credentials, but im getting the error

![image](https://cloud.githubusercontent.com/assets/4440628/22033421/6e21f3c4-dcb6-11e6-8319-997943d8269f.png)

**Comment by bestmomo** [comment]
The installer get config in **.env** file (HOST, DATABASE, USERNAME, PASSWORD), are you sure all is ok ?

**Comment by papablopo** [comment]
Yes, are the same credentials, im new in laravel, trying to debug with phpstorm and xdebug, but isnt working, so its a little dificult find where is the error

![image](https://cloud.githubusercontent.com/assets/4440628/22036524/e0e29034-dcc1-11e6-95b5-fa32ecb3bdd9.png)

**Comment by bestmomo** [comment]
Code is in **bestmomo/installer/src/Http/Controllers/DatabaseController** :

- **create** method : information is got from **.env** file to show in the form
- **store** method : after form submission config is set with form informations, **.env** is updated, and migration is launched, but for you there is an error in this place

**Comment by papablopo** [comment]
Thanks, i execute php artisan migrate:rollback, and now i have another error

> local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in C:\xampp7\htdocs\etaappbackend\vendor\laravel\framework\src\Illuminate\Hashing\BcryptHasher.php:30

**Comment by bestmomo** [comment]
Clean manualy your database

**Comment by papablopo** [comment]
Thanks, its working
