### ISSUE TITLE
PDOException SQLSTATE[HY000] [1045] Access denied for user 'myusername'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by hemakh** [bestmomo/laravel5-3-example#18]
Hi

I am using WAMP Server (version 3.0.6) on my machine. I have installed and configured as per the instructions in the README file. After changing the database details in .env file and config/database.php files, accessed the app in browser. 

1) created a database "mydb"
2) created an user "myusername" / "mypwd" and grant all privileges to this user and database.
   eg-->
            **CREATE USER 'myusername'@'localhost' IDENTIFIED BY 'mypwd';
            GRANT ALL PRIVILEGES ON * . * TO 'myusername'@'localhost';
            FLUSH PRIVILEGES;**

3) Configuration in app -->
          **.env file -->
                   DB_CONNECTION=mysql
                   DB_HOST=localhost
                   DB_PORT=3306
                   DB_DATABASE=mydb
                   DB_USERNAME=myusername
                   DB_PASSWORD=mypwd

    config/database.php -->
       'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'mydb'),
            'username' => env('DB_USERNAME', 'myusername'),
            'password' => env('DB_PASSWORD', 'mypwd'),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],**

4) In command prompt 'path/project_folder/' --->
     **php artisan cache:clear
     php artisan config:cache
     php artisan serve**

Log:
    **[2017-01-23 09:34:24] local.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'laravel53_admin'@'localhost' (using password: YES)' in C:\wamp64\www\KVM\laravel-api\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:119**

NOTE: To validate if PDO is working or not in my machine -->
Tested the mysql connection with testdb.php:
**<?php
$servername = "localhost";
$dbname = "testdb";
$username = "root";
$password = "";

// Create connection
$conn = new mysqli($servername, $username, $password);

// Check connection
if ($conn->connect_error) {
    die("<br><br>mysqli Connection failed: " . $conn->connect_error);
} 
echo "<br> mysqli Connected successfully <br>";

// Working in lcoalhost
// Create connection
$conn = mysqli_connect($servername, $username, $password);

// Check connection
if (!$conn) {
    die("<br><br>mysqli_connect Connection failed: " . mysqli_connect_error());
}
echo "<br>mysqli_connect Connected successfully<br>";

// NOt working in localhost
try {
    $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    echo "<br>MySQL PDO Connected successfully<br>"; 
    }
catch(PDOException $e)
    {
    echo "<br><br>MySQL PDO Connection failed: " . $e->getMessage();
    }
?>**

Output is 

**mysqli Connected successfully 

mysqli_connect Connected successfully

MySQL PDO Connection failed: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)**

PDO in my local machine is not working. The extensions for mysql pdo is active. Restarted WAMP server many times. But it is still not working. Can any one help?

**Comment by bestmomo** [comment]
Wamp is sometimes a bit erratic, consider rather use [Laragon](https://laragon.org/) that is perfect for Laravel.

**Comment by hemakh** [comment]
Laragon worked for migrating the tables to new database with the user credentials. Thank you for your support. 

NOTE: Can Laragon be used for production? Let me know. Soon i need to configure the same env for production.

**Comment by bestmomo** [comment]
No, Laragon is only for local development.

**Comment by hemakh** [comment]
I have accessed your repo in browser, which took into installation page with DB details. I have submitted the install/database page and I got the following error:

![screenshot](https://cloud.githubusercontent.com/assets/3335192/22208611/7e57e9c2-e1a9-11e6-9367-28bb9f9d9b32.png)

But all the data tables are installed in the configured database. So how can i access home page and start my development. 

NOTE: can i comment the line for installer class in config/app.php
**Bestmomo\Installer\InstallerServiceProvider::class,**

Edited: By commenting the above installer class, I am able to see the application home page in browser.
If this can be automated with out any error similar to Drupal or any other CMS, it will be nice.

**Comment by bestmomo** [comment]
If settings are ok installer should work.

**Comment by hemakh** [comment]
I am new to Laravel framework, Can you point me in a direction where i can use my current laravel app as a REST API with JSON input and output?

Thank you for resolving my issues, I appreciate it a lot.

**Comment by bestmomo** [comment]
Look at [this package](http://labs.infyom.com/laravelgenerator/), you can build API easily with it.

**Comment by hemakh** [comment]
Thank you. Now I am able to build a rest api on laragon with laravelgenerator by InfoOm labs and deliver the demo within less time..

**Comment by mhmalekian** [comment]
Sometimes , you must check bootstrap/cache/config.php , if you can't run "php artisan config:cache" and other commands with php artisan. I solved my problem with change database config in bootstrap/cache/config.php and then   "php artisan config:cache" performed successfully!
