### ISSUE TITLE
Not able to run the application

### ISSUE THREAD

**Issue by ankitnarang07** [bestmomo/laravel5-3-example#20]
I've installed the application following the steps mentioned in Readme file.
But when I go to path http://localhost/PROJECT_NAME/public, it simply loads the directory listing beside any webpage.

I've also created virtual host file pointing to 'public' folder with url project1.com. But that also does not help.
Can you please guide me what other steps I need to perform before I can see any web page generated.

**Comment by bestmomo** [comment]
Hello
Looks like you have a local server issue. Can you install a fresh Laravel ?

**Comment by ankitnarang07** [comment]
I've tried that, but its of no use. Still the same issue persist.

**Comment by bestmomo** [comment]
Look at the [Server Requirements](https://laravel.com/docs/5.3/installation#server-requirements) for Laravel and check yours.

**Comment by ankitnarang07** [comment]
I'm using the defined System requirements for Laravel. I'm using php version 7.1
