### ISSUE TITLE
How to redirect the admin, redactor and user

### ISSUE THREAD

**Issue by VanDxtr** [bestmomo/laravel5-3-example#21]
How to redirect the admin, redactor and user on a specific page after login

example 

Redirect admin to the admin page after login
Redirect redactor to redactor page after login
Redirect user to homepage after login

**Comment by bestmomo** [comment]
Hello

You can make that in LoginController:

> 
     public function login(LoginRequest $request)
    {
        ...

        if ($user->confirmed) {
            
            ...

            if ($request->session()->has('user_id')) {
                $request->session()->forget('user_id');
            }

            // Manage redirection with role
            switch ($user->getStatut()) {
                case 'admin':
                    // redirection for admin
                    break;
                case 'redac':
                    // redirection for redac
                    break;
                default:
                    // redirection for others
                    break;
            }
        }
        
        ...
    }
>

**Comment by VanDxtr** [comment]
thank you very much
