### ISSUE TITLE
register issue

### ISSUE THREAD

**Issue by fabianclain** [bestmomo/laravel5-3-example#23]
`Swift_TransportException in AbstractSmtpTransport.php line 383:
Expected response code 250 but got code "530", with message "530 5.7.1 Authentication required
"`

**Comment by bestmomo** [comment]
Check your email configuration in **.env** file.

**Comment by fabianclain** [comment]
MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525 
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

What do I need to change and how?

**Comment by bestmomo** [comment]
You must set config according to email service you use.

**Comment by fabianclain** [comment]
indeed, setting the email address fixes the repository.
