### ISSUE TITLE
sweet alert absent de back.css ?

### ISSUE THREAD

**Issue by gilr** [bestmomo/laravel5-3-example#5]
Les messages de confirmation de destruction ne s'affichent pas (ou sont noyés dans le bas noir de la page d'admin) -> peut-être qu'il n'y a qu'a re-générer le fichier back.css (duquel est absent sweetalert.css) mais comme je n'utilise pas elixir, gulp et sass, je n'en suis pas certain...

Gil

**Comment by bestmomo** [comment]
Ah oui je n'ai pas mis à jour les CSS dans le repo, je corrige ça ;)  sinon effectivement il suffit de les régénérer avec elixir, l'essayer c'est l'adopter !

C'est fait sur ce commit : https://github.com/bestmomo/laravel5-3-example/commit/262942f061d9a89c7a9dd2fd857d5d2ddc297ca6

**Comment by gilr** [comment]
Ca marche, beaucoup plus joli !

**Comment by bestmomo** [comment]
Oui c'est quand même mieux que les boîtes JavaScript par défaut !
