### ISSUE TITLE
composer install --no-dev fails

### ISSUE THREAD

**Issue by tunele** [bestmomo/laravel5-3-example#7]
First of all, thanks for your great job!
I get this error if I try composer install --no-dev

Generating autoload files

> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize

  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Magyarjeti\LaravelLipsum\LipsumServiceProvider' not found  

Script php artisan optimize handling the post-install-cmd event returned with error code 1

**Comment by bestmomo** [comment]
Hello,

Thank you for review.

Fixed with [this commit](https://github.com/bestmomo/laravel5-3-example/commit/fabef2294ec825b240a3f8884864adeb81db5e8c).

**Comment by tunele** [comment]
fixed, thanks a lot bestmomo
