### ISSUE TITLE
Email Content

### ISSUE THREAD

**Issue by ghost** [bestmomo/laravel5-3-example#8]
I know it's probably a simple solution, but considering I'm kinda new to Laravel I can't find where exactly are the variables to modify the content of E-mails is, I tried modifying: Verify.php but it only gave me limited content to modify and not the entire message I want to display to the user.

Any help on this would be great!

**Comment by bestmomo** [comment]
Hello

Emails are built in notifications (look at **Notifications** folder).

**Comment by ghost** [comment]
Thank you it worked!
