### ISSUE TITLE
TokenMismatchException in VerifyCsrfToken.php

### ISSUE THREAD

**Issue by deltace** [bestmomo/laravel5-3-example#9]
Après connexion, je me retrouve avec cette erreur. Pourtant j'ai suivi votre tutoriel. J'ai peut être oublié quelque chose ?

**Comment by bestmomo** [comment]
Bonjour,
Il faudrait vérifier que les sessions fonctionnent bien.

**Comment by deltace** [comment]
Bonjour,
Une idée sur la manière de vérifier le fonctionnement des sessions ?

**Comment by bestmomo** [comment]
Sur n'importe quelle page commencer par mettre session()->put('cle', 'valeur') pour mémoriser une infomation en session et relancer la page avec un dd(session('cle')) dans le code.

**Comment by cotiga** [comment]
Bonjour,
En local via MAMP, même problème :
TokenMismatchException in VerifyCsrfToken.php line 68:
dd(session... retourne null
:/

**Comment by bestmomo** [comment]
[Ce fil](http://stackoverflow.com/questions/20034838/session-problems-on-mamp) peut peut-être aider.

**Comment by deltace** [comment]
Je crois que j'ai trouvé d'ou provient le soucis. Cela vient de Safari/OS X. Car en testant sur Chrome pas de soucis.

**Comment by cotiga** [comment]
J'ai modifié le php.ini, essayer d'autres navigateurs... rien y fait.
Je crois que mon mon 10.9 est au bout du rouleau. Je vais essayé sur un bon Ubuntu tout neuf et vous dirais.
En attendant merci

**Comment by cotiga** [comment]
Hi,
Avec mon Mac, rien à faire :/
Sous Ubuntu, nickel.
Merci
